const actionsType = {
    FETCH_USERS : "FETCH_USERS",
    FETCH_USERS_REJECTED : "FETCH_USERS_REJECTED",
    FETCH_USER : "FETCH_USER",
    FETCH_USER_REJECTED : "FETCH_USER_REJECTED",
    FETCH_RESTAURANTS : "FETCH_RESTAURANTS",
    FETCH_RESTAURANTS_REJECTED : "FETCH_RESTAURANTS_REJECTED",

}

const consts = {
    ACTIONS_TYPE : actionsType,
}

module.exports = consts