const actionsType = {
    FETCH_USERS : "FETCH_USERS",
    FETCH_USERS_REJECTED : "FETCH_USERS_REJECTED",
    FETCH_USER : "FETCH_USER",
    FETCH_USER_REJECTED : "FETCH_USER_REJECTED",
    FETCH_RESTAURANTS : "FETCH_RESTAURANTS",
    FETCH_RESTAURANTS_REJECTED : "FETCH_RESTAURANTS_REJECTED",
    FETCH_VOTE : "FETCH_VOTE",
    FETCH_VOTE_REJECTED : "FETCH_VOTE_REJECTED",

    FETCH_WINNER_DAY : "FETCH_WINNER_DAY",
    FETCH_WINNER_DAY_REJECTED : "FETCH_WINNER_DAY_REJECTED",
    FETCH_WINNERS_WEEK : "FETCH_WINNERS_WEEK",
    FETCH_WINNERS_DAY_REJECTED : "FETCH_WINNERS_WEEK_REJECTED",

    FETCH_HAS_VOTE : "FETCH_HAS_VOTE",
    FETCH_HAS_VOTE_REJECTED : "FETCH_HAS_VOTE_REJECTED",


}

const consts = {
    ACTIONS_TYPE : actionsType,
}

module.exports = consts